target_column: 'loan_approved'
test_fraction: 0.3
random_state: 13
to_feature_store: True
drop_highly_correlated: True
feature_selection: "rfe"
use_feature_selection: True
baseline_model_params:
  n_estimators: 100
  max_depth: 5
  max_features: 20
  random_state: 13
feature_columns: ["col1", "col2", "col3"]  
psi_bins: 10
output_dir: "data/08_reporting"
