target_column: 'loan_approved'
test_fraction: 0.3
random_state: 13
to_feature_store: True
drop_highly_correlated: True
feature_selection: "rfe"
use_feature_selection: True
baseline_model_params:
  n_estimators: 100
  max_depth: 5
  max_features: 20
  random_state: 13
feature_columns:
  - no_of_dependents
  - self_employed
  - income_annum
  - loan_amount
  - loan_term
  - cibil_score
  - residential_assets_value
  - commercial_assets_value
  - luxury_assets_value
  - bank_asset_value
  - graduate 
psi_bins: 10
output_dir: "data/08_reporting"
production_model_path: data/06_models/production_model.pkl
production_columns_path: data/06_models/production_cols.pkl
production_metrics_path: data/08_reporting/production_model_metrics.json
save_path: "data/08_reporting"
chunk_size: 100             
drift_threshold: 0.2        


